[package]
name = "where_from"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = "1"
xattr = "1"

[[bin]]
name = "where-from"
path = "src/main.rs"
